/********************************************************************
* rootdict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error rootdict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablerootdict();
extern void G__cpp_setup_inheritancerootdict();
extern void G__cpp_setup_typetablerootdict();
extern void G__cpp_setup_memvarrootdict();
extern void G__cpp_setup_globalrootdict();
extern void G__cpp_setup_memfuncrootdict();
extern void G__cpp_setup_funcrootdict();
extern void G__set_cpp_environmentrootdict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "RDK2CutSet.h"
#include "RDK2Set.h"
#include "RDK2MCAnalyzer.h"
#include "RDK2ExpAnalyzer.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__rootdictLN_TClass;
extern G__linked_taginfo G__rootdictLN_TBuffer;
extern G__linked_taginfo G__rootdictLN_TMemberInspector;
extern G__linked_taginfo G__rootdictLN_TObject;
extern G__linked_taginfo G__rootdictLN_TNamed;
extern G__linked_taginfo G__rootdictLN_TString;
extern G__linked_taginfo G__rootdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__rootdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rootdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__rootdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rootdictLN_ParType;
extern G__linked_taginfo G__rootdictLN_EveType;
extern G__linked_taginfo G__rootdictLN_CoDet;
extern G__linked_taginfo G__rootdictLN_TCut;
extern G__linked_taginfo G__rootdictLN_RDK2CutSet;
extern G__linked_taginfo G__rootdictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__rootdictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__rootdictLN_TH1;
extern G__linked_taginfo G__rootdictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__rootdictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__rootdictLN_TH2D;
extern G__linked_taginfo G__rootdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__rootdictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__rootdictLN_TChain;
extern G__linked_taginfo G__rootdictLN_HistDim;
extern G__linked_taginfo G__rootdictLN_RDK2Set;
extern G__linked_taginfo G__rootdictLN_RDK2MCAnalyzer;
extern G__linked_taginfo G__rootdictLN_RDK2ExpAnalyzer;

/* STUB derived class for protected member access */
